### ISSUE TITLE
remove use of legacy NOT_NULL comparison operator

### ISSUE THREAD

**Issue by whyvez** [awslabs/dynamodb-document-js-sdk#14]
In you examples and tests you use the ``NOT_NULL`` comparison operator. Seems like this is a legacy feature and that projections should be used instead. 

http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/LegacyConditionalParameters.html

How would you query items using projections where the range key is x but you don't really care about the hash key? i.e. similar to your house query in your **Condition Object** section of your README.

**Comment by raymolin** [comment]
The NOT_NULL operator is still necessary for certain customer use cases, especially since KeyConditions don't support expressions yet (I assume that's what you mean by projections).  Currently, the best way to do a leading range query (where you disregard the hash key and condition only on range key) is perform an index scan with filter expression.
