### ISSUE TITLE
Need more sample examples to illustrate CRUD operations

### ISSUE THREAD

**Issue by hodiapa** [awslabs/dynamodb-document-js-sdk#36]
need more sample examples as to how CRUD operations can be implemented using this sdk.

**Comment by raymolin** [comment]
The functionality of this SDK is completely reliant on the AWS-SDK.  Essentially, a lot of the request will looks similar, but instead of having to input {S: "string"}, you can have your parameters as a primitive, "string".  However, if you go through the JS Shell tutorial for DynamoDB http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Tools.DynamoDBLocal.Shell.html,you can see a ton of different operations.  In addition, there are plenty of templates in the shell that will allow you to see most of the operations.  Type in something like "ge" (short for getItem), hit ctrl + enter and go to town.

**Comment by hodiapa** [comment]
Something like this will be really helpful for js sdk:

http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/JavaCRUDHighLevelExample1.html

**Comment by amcp** [comment]
http://docs.aws.amazon.com/amazondynamodb/latest/gettingstartedguide/GettingStarted.NodeJs.03.html#GettingStarted.NodeJs.03.03
